#!/usr/bin/env python3
"""Emits Tests/toolschemas.inc from Sources/CrucibleKit/ToolSurface.swift.

The golden suite proves that CrucibleKit's chat template and the C oracle build
the same system turn from the same tools.  That only means something if the
tools ARE the same, and for a while they were the same only because someone had
transcribed twelve JSON schemas into C by hand.  Editing one tool description
then broke the goldens with a diff about the description rather than about the
template -- a real failure, but a misleading one.

So the C side now reads the Swift side.  One definition, in the file the app
actually ships, and the goldens go back to testing the template.
"""
import json
import re
import sys

SRC = "Sources/CrucibleKit/ToolSurface.swift"


def schemas(src):
    text = open(src).read()
    order = re.search(r"public static let guestSchemas: \[String\] = \[(.*?)\]",
                      text, re.S)
    if not order:
        sys.exit("cannot find guestSchemas in " + src)
    names = re.findall(r"\b(\w+Schema)\b", order.group(1))

    out = []
    for name in names:
        m = re.search(r'public static let %s = #"""\n(.*?)\n    """#' % name,
                      text, re.S)
        if not m:
            sys.exit("cannot find %s in %s" % (name, src))
        blob = m.group(1).strip()
        json.loads(blob)          # a broken schema fails here, not at runtime
        out.append((name, blob))
    return out


def c_literal(blob):
    """One C string literal per ~70 columns, escaped."""
    esc = blob.replace("\\", "\\\\").replace('"', '\\"')
    esc = esc.replace("\n", "\\n").replace("\t", "\\t")
    lines, cur = [], ""
    i = 0
    while i < len(esc):
        # Never split an escape sequence across two literals.
        step = 2 if esc[i] == "\\" else 1
        cur += esc[i:i + step]
        i += step
        if len(cur) >= 68:
            lines.append(cur)
            cur = ""
    if cur:
        lines.append(cur)
    return "\n".join('"%s"' % l for l in lines)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else SRC
    got = schemas(src)
    print("/* GENERATED by tools/schemas2c.py from %s -- do not edit. */" % src)
    print("/* %d tools, in guestSchemas order. */" % len(got))
    for name, blob in got:
        print("\n/* %s */" % name)
        print(c_literal(blob) + ",")


if __name__ == "__main__":
    main()
