/* bin2c: turn source files into a C string literal for embedding.
 *
 * Metal kernels are kept as separate .metal files for review, then embedded
 * into the binary as one concatenated source string.  The runtime compiles
 * that string with newLibraryWithSource: -- which, unlike a build-time
 * .metallib, does not require the (separately downloadable) Metal toolchain,
 * and leaves qwasar a single relocatable binary with no runtime dependency on
 * its source tree.
 *
 *   bin2c <symbol> <file>...  > out.inc
 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: bin2c <symbol> <file>...\n"); return 2; }
    printf("/* Generated by tools/bin2c.c -- do not edit. */\n");
    printf("static const char %s[] =\n", argv[1]);
    for (int i = 2; i < argc; i++) {
        FILE *f = fopen(argv[i], "rb");
        if (!f) { perror(argv[i]); return 1; }
        printf("/* ---- %s ---- */\n\"\\n\"\n\"", argv[i]);
        int c, col = 0;
        while ((c = fgetc(f)) != EOF) {
            switch (c) {
            case '\n': printf("\\n\"\n\""); col = 0; continue;
            case '\r': continue;
            case '"':  printf("\\\""); col += 2; break;
            case '\\': printf("\\\\"); col += 2; break;
            case '\t': printf("\\t");  col += 2; break;
            case '?':  printf("\\?");  col += 2; break; /* defeat trigraphs */
            default:
                if (c < 32 || c > 126) { printf("\\%03o", c); col += 4; }
                else { putchar(c); col++; }
            }
            /* Keep lines short enough for any compiler's string-literal limits. */
            if (col > 1000) { printf("\"\n\""); col = 0; }
        }
        printf("\"\n");
        fclose(f);
    }
    printf(";\n");
    return 0;
}
