#!/usr/bin/env python3
"""Generate qwasar_unicode.inc -- codepoint range tables for the pre-tokenizer.

DEV ONLY.  The output is checked in, so building qwasar never needs Python.
Re-run only to move to a newer Unicode version:

    python3 tools/gen_unicode.py > qwasar_unicode.inc
"""
import sys
import unicodedata

MAX = 0x110000


def ranges(pred):
    out, start = [], None
    for cp in range(MAX):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def is_letter(cp):
    return unicodedata.category(chr(cp)).startswith("L")


def is_number(cp):
    return unicodedata.category(chr(cp)).startswith("N")


def is_space(cp):
    ch = chr(cp)
    # Matches what a regex engine treats as \s: Unicode whitespace plus the
    # ASCII control whitespace that isspace() already covers.
    return ch.isspace() or unicodedata.category(ch) in ("Zs", "Zl", "Zp")


def emit(name, rs):
    print(f"static const qw_cp_range qw_{name}_ranges[] = {{")
    for i in range(0, len(rs), 4):
        row = "".join("{0x%05X,0x%05X}," % r for r in rs[i:i + 4])
        print("    " + row)
    print("};")
    print(f"#define QW_{name.upper()}_COUNT "
          f"(sizeof qw_{name}_ranges / sizeof *qw_{name}_ranges)")
    print()


def main():
    print("/* Generated by tools/gen_unicode.py -- do not edit.")
    print(f" * Unicode {unicodedata.unidata_version}. */")
    print()
    print("typedef struct { uint32_t lo, hi; } qw_cp_range;")
    print()
    for name, pred in (("letter", is_letter), ("number", is_number), ("space", is_space)):
        rs = ranges(pred)
        print(f"/* \\p{{{name[0].upper()}}}: {len(rs)} ranges */", file=sys.stderr)
        emit(name, rs)


if __name__ == "__main__":
    main()
